const AreaTypes = {
  FETCH_AREAS_OBJECT: 'FETCH_AREAS_OBJECT',
  FETCH_AREAS_SUCCESS: 'FETCH_AREAS_SUCCESS',
  FETCH_AREAS_FAIL: 'FETCH_AREAS_FAIL',
  FETCH_AREA_OBJECT: 'FETCH_AREA_OBJECT',
  FETCH_AREA_SUCCESS: 'FETCH_AREA_SUCCESS',
  FETCH_AREA_FAIL: 'FETCH_AREA_FAIL',
};

export default AreaTypes;
