const BookTypes = {
  FETCH_BOOKS_OBJECT: 'FETCH_BOOKS_OBJECT',
  FETCH_BOOKS_SUCCESS: 'FETCH_BOOKS_SUCCESS',
  FETCH_BOOKS_FAIL: 'FETCH_BOOKS_FAIL',
  FETCH_BOOK_OBJECT: 'FETCH_BOOK_OBJECT',
  FETCH_BOOK_SUCCESS: 'FETCH_BOOK_SUCCESS',
  FETCH_BOOK_FAIL: 'FETCH_BOOK_FAIL',
};

export default BookTypes;
