const ClimbTypes = {
  FETCH_CLIMBS_OBJECT: 'FETCH_CLIMBS_OBJECT',
  FETCH_CLIMBS_SUCCESS: 'FETCH_CLIMBS_SUCCESS',
  FETCH_CLIMBS_FAIL: 'FETCH_CLIMBS_FAIL',
  FETCH_CLIMB_OBJECT: 'FETCH_CLIMB_OBJECT',
  FETCH_CLIMB_SUCCESS: 'FETCH_CLIMB_SUCCESS',
  FETCH_CLIMB_FAIL: 'FETCH_CLIMB_FAIL',
};

export default ClimbTypes;
