const RegionTypes = {
  FETCH_REGIONS_OBJECT: 'FETCH_REGIONS_OBJECT',
  FETCH_REGIONS_SUCCESS: 'FETCH_REGIONS_SUCCESS',
  FETCH_REGIONS_FAIL: 'FETCH_REGIONS_FAIL',
  FETCH_REGION_OBJECT: 'FETCH_REGION_OBJECT',
  FETCH_REGION_SUCCESS: 'FETCH_REGION_SUCCESS',
  FETCH_REGION_FAIL: 'FETCH_REGION_FAIL',
};

export default RegionTypes;
