const RouteTypes = {
  FETCH_ROUTES_OBJECT: 'FETCH_ROUTES_OBJECT',
  FETCH_ROUTES_SUCCESS: 'FETCH_ROUTES_SUCCESS',
  FETCH_ROUTES_FAIL: 'FETCH_ROUTES_FAIL',
  FETCH_ROUTE_OBJECT: 'FETCH_ROUTE_OBJECT',
  FETCH_ROUTE_SUCCESS: 'FETCH_ROUTE_SUCCESS',
  FETCH_ROUTE_FAIL: 'FETCH_ROUTE_FAIL',
};

export default RouteTypes;
