const SharedTypes = {
  USER_CLIMB_OBJECT: 'USER_CLIMB_OBJECT',
  UNKOWN_ERROR_OBJECT: 'UNKNOWN_ERROR_OBJECT',
  ADD_TODO_OBJECT: 'ADD_TODO_OBJECT',
  ADD_COMPLETION_OBJECT: 'ADD_COMPLETION_OBJECT',
  REMOVE_USER_CLIMB_OBJECT: 'REMOVE_USER_CLIMB_OBJECT',
};

export default SharedTypes;
