const SubareaTypes = {
  FETCH_SUBAREAS_OBJECT: 'FETCH_SUBAREAS_OBJECT',
  FETCH_SUBAREAS_SUCCESS: 'FETCH_SUBAREAS_SUCCESS',
  FETCH_SUBAREAS_FAIL: 'FETCH_SUBAREAS_FAIL',
};

export default SubareaTypes;
