const SubareaTypes = {
  FETCH_SUBAREAS_OBJECT: 'FETCH_SUBAREAS_OBJECT',
  FETCH_SUBAREAS_SUCCESS: 'FETCH_SUBAREAS_SUCCESS',
  FETCH_SUBAREAS_FAIL: 'FETCH_SUBAREAS_FAIL',
  FETCH_SUBAREA_OBJECT: 'FETCH_SUBAREA_OBJECT',
  FETCH_SUBAREA_SUCCESS: 'FETCH_SUBAREA_SUCCESS',
  FETCH_SUBAREA_FAIL: 'FETCH_SUBAREA_FAIL',
};

export default SubareaTypes;
