const SubregionTypes = {
  FETCH_SUBREGIONS_OBJECT: 'FETCH_SUBREGIONS_OBJECT',
  FETCH_SUBREGIONS_SUCCESS: 'FETCH_SUBREGIONS_SUCCESS',
  FETCH_SUBREGIONS_FAIL: 'FETCH_SUBREGIONS_FAIL',
};

export default SubregionTypes;
