const SubregionTypes = {
  FETCH_SUBREGIONS_OBJECT: 'FETCH_SUBREGIONS_OBJECT',
  FETCH_SUBREGIONS_SUCCESS: 'FETCH_SUBREGIONS_SUCCESS',
  FETCH_SUBREGIONS_FAIL: 'FETCH_SUBREGIONS_FAIL',
  FETCH_SUBREGION_OBJECT: 'FETCH_SUBREGION_OBJECT',
  FETCH_SUBREGION_SUCCESS: 'FETCH_SUBREGION_SUCCESS',
  FETCH_SUBREGION_FAIL: 'FETCH_SUBREGION_FAIL',
};

export default SubregionTypes;
