const UserBookTypes = {
  LIKE_REQUEST: 'LIKE_REQUEST',
  ERROR_REQUEST: 'ERROR_REQUEST',
  UNLIKE_REQUEST: 'UNLIKE_REQUEST',
  ADD_TO_CART_REQUEST: 'ADD_TO_CART_REQUEST',
  REMOVE_FROM_CART_REQUEST: 'REMOVE_FROM_CART_REQUEST',
};

export default UserBookTypes;
